name: infinite_overlapped_carousel
description: A Flutter package project that is a simple horizontal overlapped_carousel widget.
version: 1.0.2

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/